version: "3.4"
services:
  webapigateway:
    image: ${Docker_Registry}-webapigateway
    build:
      context: .
      dockerfile: src/ApiGateway/Web.ApiGateway/Dockerfile
    container_name: c_webapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=${Stage}
      - ASPNETCORE_URLS=http://+:${WebApiGateway_Port}
      - ServiceConfig__serviceName=webapigateway
    ports:
      - "${WebApiGateway_Port}:${WebApiGateway_Port}"
    networks:
      - net_backendservices
    env_file:
      - ./.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
  adminidentityservice:
    image: ${Docker_Registry}-adminidentityservice
    build:
      context: .
      dockerfile: src/Services/AdminIdentityServices/AdminIdentityService/Dockerfile
    container_name: c_adminidentityservice
    environment:
      - ASPNETCORE_ENVIRONMENT=${Stage}
      - ASPNETCORE_URLS=http://+:${AdminIdentity_Port}
      - ServiceConfig__serviceName=c_adminidentityservice
    ports:
      - "${AdminIdentity_Port}:${AdminIdentity_Port}"
    networks:
      - net_backendservices
    env_file:
      - ./.env
    depends_on:
      - webapigateway
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
networks:
  net_frontend:
    driver: bridge
    external: true
  net_backendservices:
    driver: bridge
    external: true
