version: "3.4"

services:
  s_rabbitmq:
    container_name: c_rabbitmq
    image: rabbitmq:3-management
    ports:
      - ${RabbitMq_TCP_Port}:${RabbitMq_TCP_Port}
      - ${RabbitMq_UI_Port}:${RabbitMq_UI_Port}
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - net_backendservices
      - net_frontend
    env_file:
      - ./.env
  s_redis:
    container_name: c_redis
    image: redis
    ports:
      - ${Redis__Port}:${Redis__Port}
    networks:
      - net_backendservices
    env_file:
      - ./.env
    volumes:
      - /path/to/local/dаta:/root/redis
    command: redis-server --requirepass squba
    environment:
      - REDIS_PASSWORD=${Redis__Password}
      - REDIS_PORT=${Redis__Port}
      - REDIS_REPLICATION_MODE=master
  s_sqlserver:
    container_name: c_sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - ${SQL_Host_Port}:${SQL_TCP_Port}
    env_file:
      - ./.env
    environment:
      - ACCEPT_EULA=${SQL_User}
      - MSSQL_SA_PASSWORD=${SQL_Password}
      - MSSQL_PID=Standard
      - MSSQL_AGENT_ENABLED=true
    volumes:
      - sqlserver_data:/var/opt/mssql/data
      - sqlserver_log:/var/opt/mssql/log
    networks:
      - net_backendservices
  # s_nginx:
  #   container_name: c_nginx
  #   image: nginx
  #   ports:
  #     - ${Nginx_Port}:80
  #   env_file:
  #     - ./.env
  s_prometheus:
    image: prom/prometheus
    container_name: c_prometheus
    restart: unless-stopped
    ports:
      - "${Prometheus_Port}:9090"
    environment:
      - TZ=UTC
    volumes:
      - ./Docker/Config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./Docker/PrometheusData:/prometheus/data
    command:
      - '--storage.tsdb.retention.time=0s'
      - '--storage.tsdb.retention.size=2KB'
      - '--config.file=/etc/prometheus/prometheus.yml'  
    links:
      - s_cadvisor:cadvisor
      - s_node-exporter:node-exporter
    env_file:
      - ./.env       
  s_grafana:
    image: grafana/grafana
    container_name: c_grafana
    ports:
      - "${Grafana_Port}:3000"
    volumes:
      - ./Docker/MetricData/grafana-data/data:/var/lib/grafana
    links:
      - s_prometheus:prometheus
    restart: unless-stopped
    env_file:
      - ./.env
  s_node-exporter:
    image: prom/node-exporter:latest
    container_name: c_node-exporter
    restart: unless-stopped
    expose:
      - 9100
  s_cadvisor:
    image: google/cadvisor:latest
    container_name: c_cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
  s_elasticsearch:
    container_name: c_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    env_file:
      - ./.env
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.monitoring.enabled=false
      - xpack.monitoring.collection.enabled=false
      - ELASTIC_PASSWORD=${ElasticSearch_Password}
      - ELASTICSEARCH_USERNAME=${ElasticSearch_UserName}
      # - discovery.type=single-node           
      # Uzaktan bağlantıyı açmak için
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "${Elastic_TCP_Port}:9200"
      - "${Elastic_UDP_Port}:9300"
    networks:
      - net_backendservices
  s_mongo:
    container_name: c_mongo
    image: mongo
    ports:
      - ${Mongo_Port}:${Mongo_Port}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${Mongo_UserName}
      MONGO_INITDB_ROOT_PASSWORD: ${Mongo_Password}
    networks:
      - net_backendservices
    env_file:
      - ./.env
  s_zookeeper:
    container_name: c_zookeeper
    image: debezium/zookeeper
    ports:
      - "${Zookeeper_Port}:${Zookeeper_Port}"
      - "2888:2888"
      - "3888:3888"
    networks:
      - net_backendservices
    env_file:
      - ./.env
  s_kafka:
    container_name: c_kafka
    image: debezium/kafka
    ports:
      - "${Kafka_TCP_Port}:${Kafka_TCP_Port}"
      - "${Kafka_External_Tcp}:${Kafka_External_Tcp}"
    depends_on:
      - s_zookeeper
    environment:
      - ZOOKEEPER_CONNECT=s_zookeeper:${Zookeeper_Port}
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_EXT://s_kafka:${Kafka_External_Tcp},LISTENER_INT://s_kafka:${Kafka_TCP_Port}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INT:PLAINTEXT,LISTENER_EXT:PLAINTEXT
      - KAFKA_LISTENERS=LISTENER_INT://s_kafka:${Kafka_TCP_Port},LISTENER_EXT://s_kafka:${Kafka_External_Tcp}
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INT
    networks:
      - net_backendservices
    env_file:
      - ./.env
  s_debeziumconnect:
    container_name: c_debeziumconnect
    image: debezium/connect
    ports:
      - ${Debeziumconnect_Port}:${Debeziumconnect_Port}
    environment:
      - BOOTSTRAP_SERVERS=s_kafka:${Kafka_TCP_Port}
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - s_zookeeper
      - s_kafka
    networks:
      - net_backendservices
    env_file:
      - ./.env  
  s_zipkin:
    container_name: c_zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - net_backendservices
networks:
  net_frontend:
    driver: bridge
    external: true
  net_backendservices:
    driver: bridge
    external: true

volumes:
  rabbitmq:
  sqlserver_data:
  sqlserver_log:
