global:
  scrape_interval: 600s
  scrape_timeout: 595s
  evaluation_interval: 600s
alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets: []
scrape_configs:
- job_name: AdminIdentityService
  honor_timestamps: true
  scrape_interval: 600s  
  scrape_timeout: 595s  
  metrics_path: /metrics
  scheme: http  
  static_configs:  
  - targets:  
    - host.docker.internal:4001