// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator
{
    internal sealed partial class Vsix
    {
        public const string Id = "Generator.e2955b9f-4623-41b4-8441-2be5e8db1ebe";
        public const string Name = "STemplateGen";
        public const string Description = @"STemplate Generator";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Semih Ötün";
        public const string Tags = "";
    }
}
