// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GeneratorString = "76154e61-6153-49ca-bfcd-f3f884812e3d";
        public static Guid Generator = new Guid(GeneratorString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int GeneratorItemNodeGroup = 0x0002;
        public const int MediatRCreateAddHandlerCommand = 0x0100;
        public const int GeneratorItemNodeSubMenu = 0x11100;
        public const int MediatRCreateDeleteHandlerCommand = 0x0010;
        public const int MediatRCreateUpdateHandlerCommand = 0x0210;
        public const int MediatRCreateGridHandlerCommand = 0x0202;
        public const int MediatRCreateGetByIdHandlerCommand = 0x0201;
        public const int MediatRCreateGetAllListdHandlerCommand = 0x0211;
        public const int GeneratorSettingNodeGroup = 0x0101;
        public const int GeneratorSettingSubMenu = 0x0102;
        public const int GeneratorSettingsCommand = 0x0103;
        public const int MediatRCreateCQRSCommand = 0x0111;
        public const int ClassCreateVoidCommand = 0x1112;
    }
}