// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator
{
    internal sealed partial class Vsix
    {
        public const string Id = "Generator.671472b7-a36b-4260-a8e0-23cffd780f5d";
        public const string Name = "Generator";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
